import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ReactNode } from 'react';
import AuthSession from './_component/AuthSession';
import { MSWProvider } from './_component/MSWComponent';
import './globals.css';

if (
  process.env.NEXT_RUNTIME === 'nodejs' &&
  process.env.NODE_ENV !== 'production' &&
  process.env.NEXT_PUBLIC_API_MOCKING !== 'disabled'
) {
  console.log('MSW 서버 실행??????');
  const { server } = require('@/mocks/http.ts');
  server.listen();
} else {
  console.log('MSW 서버 실행 안함');
}

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <MSWProvider>
          <AuthSession>{children}</AuthSession>
        </MSWProvider>
      </body>
    </html>
  );
}
